In [14]:
import numpy as np
import scipy.signal as scipysig
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
A = np.array(
    [[-1, -4, 0, 0, 0],
     [4, -1, 0, 0, 0],
     [0, 0, -3, 1, 0],
     [0, 0, -1, -3, 0],
     [0, 0, 0, 0, -2]])
B = np.ones((5, 1))
C = np.array([1, 0, 0, 0, 0])
D = np.array([0])


dim_x = A.shape[0]
dim_u = 1
dt = 0.05
A,B,C,D,_ = scipysig.cont2discrete(system=(A,B,C,D), dt = dt)


In [25]:
# Simulate system
steps = 1000
std_noise = 0
U = np.zeros((dim_u, steps))
X = np.zeros((dim_x, steps + 1))
X[:, 0] = np.random.normal(size=(dim_x))

DeltaU = np.zeros((dim_u, steps))


for i in range(steps):
    U[:, i] = np.random.normal(size=(dim_u))
    X[:, i+1] = A @ X[:, i] +  np.squeeze(B * U[:, i]) + std_noise * np.random.normal(size=(dim_x))

Xp = X[:, 1:]
Xm = X[:, :-1]
Um = U

DeltaU =  np.random.normal(size=(U.shape)) # - U

print('------ CLASSICAL SYS ID  ------')
AB = Xp @ np.linalg.pinv(np.vstack((Xm, Um)))
print(AB)
print('------ CORRUPTED SYS ID  ------')
AB_corrupted = Xp @ np.linalg.pinv(np.vstack((Xm, Um + DeltaU)))
print(AB_corrupted)
DeltaAB = - B @ DeltaU @ np.linalg.pinv(np.vstack((Xm, Um + DeltaU)))
print(DeltaAB)
P = np.vstack((Xm, Um + DeltaU))
print(np.linalg.norm(np.linalg.pinv((Um + DeltaU))))
print(np.linalg.norm(B @ DeltaU @ np.linalg.pinv((Um + DeltaU))) )
print(np.linalg.norm(DeltaU @ (Um + DeltaU).T))
print(np.linalg.norm(DeltaU @ (Um + DeltaU).T))
print(DeltaU @ (Xm).T)

------ CLASSICAL SYS ID  ------
[[0.932 -0.189 -0.000 0.000 0.000 0.044]
 [0.189 0.932 0.000 -0.000 -0.000 0.053]
 [0.000 -0.000 0.860 0.043 -0.000 0.048]
 [0.000 0.000 -0.043 0.860 -0.000 0.045]
 [-0.000 0.000 0.000 -0.000 0.905 0.048]]
------ CORRUPTED SYS ID  ------
[[0.939 -0.186 0.055 -0.055 -0.026 0.022]
 [0.197 0.936 0.067 -0.068 -0.031 0.027]
 [0.008 0.003 0.920 -0.017 -0.028 0.024]
 [0.007 0.003 0.014 0.802 -0.027 0.023]
 [0.008 0.004 0.060 -0.060 0.877 0.024]]
[[0.007 0.003 0.055 -0.055 -0.026 -0.021]
 [0.008 0.004 0.067 -0.068 -0.031 -0.026]
 [0.008 0.003 0.060 -0.060 -0.028 -0.023]
 [0.007 0.003 0.057 -0.057 -0.027 -0.022]
 [0.008 0.004 0.060 -0.060 -0.028 -0.023]]
0.02313626210386071
0.05192258868370033
911.8501061432706
911.8501061432706
[[-2.695 1.121 2.702 1.151 4.279]]


(array([110.586, 29.253, 16.862, 1.988, 1.294, 0.036]),
 array([[0.154, 0.371, 0.898, 0.072, 0.160, 0.022],
        [0.056, 0.865, -0.387, -0.226, 0.219, -0.018],
        [-0.012, -0.023, -0.141, 0.592, 0.504, 0.613],
        [0.037, 0.307, -0.031, 0.440, -0.807, 0.243],
        [0.006, 0.072, -0.089, 0.632, 0.149, -0.752],
        [-0.986, 0.120, 0.119, 0.012, 0.002, -0.001]]))