In [22]:
import numpy as np
import scipy.signal as scipysig
# np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
A = np.array(
    [[-1, -4, 0, 0, 0],
     [4, -1, 0, 0, 0],
     [0, 0, -3, 1, 0],
     [0, 0, -1, -3, 0],
     [0, 0, 0, 0, -2]])
B = np.ones((5, 1))
C = np.array([1, 0, 0, 0, 0])
D = np.array([0])


dim_x = A.shape[0]
dim_u = 1
dt = 0.05
A,B,C,D,_ = scipysig.cont2discrete(system=(A,B,C,D), dt = dt)


In [32]:
# Simulate system
steps = 100
std_noise = 0
U = np.zeros((dim_u, steps))
X = np.zeros((dim_x, steps + 1))
X[:, 0] = np.random.normal(size=(dim_x))

DeltaU = np.zeros((dim_u, steps))


for i in range(steps):
    U[:, i] = np.random.normal(size=(dim_u))
    X[:, i+1] = A @ X[:, i] +  np.squeeze(B * U[:, i]) + std_noise * np.random.normal(size=(dim_x))

Xp = X[:, 1:]
Xm = X[:, :-1]
Um = U

DeltaU = -U + np.random.normal(size=(U.shape))

print('------ CLASSICAL SYS ID  ------')
AB = Xp @ np.linalg.pinv(np.vstack((Xm, Um)))
#print(AB)
print('------ CORRUPTED SYS ID  ------')
AB_corrupted = Xp @ np.linalg.pinv(np.vstack((Xm, Um + DeltaU)))
#print(AB_corrupted)
DeltaAB = - B @ DeltaU @ np.linalg.pinv(np.vstack((Xm, Um + DeltaU)))
#print(DeltaAB)
P = np.vstack((Xm, Um + DeltaU))
P = P @ P.T
np.linalg.eig(P)


------ CLASSICAL SYS ID  ------
------ CORRUPTED SYS ID  ------


(array([94.266, 14.696, 10.571, 2.609, 0.506, 0.030]),
 array([[0.043, -0.853, 0.431, -0.216, -0.189, 0.042],
        [-0.021, 0.373, 0.882, 0.287, -0.001, 0.010],
        [-0.015, 0.107, 0.164, -0.619, 0.460, -0.606],
        [-0.008, 0.274, 0.005, -0.366, -0.860, -0.229],
        [-0.019, 0.209, 0.096, -0.595, 0.118, 0.761],
        [0.999, 0.052, 0.004, -0.009, 0.010, 0.002]]))

(array([110.586, 29.253, 16.862, 1.988, 1.294, 0.036]),
 array([[0.154, 0.371, 0.898, 0.072, 0.160, 0.022],
        [0.056, 0.865, -0.387, -0.226, 0.219, -0.018],
        [-0.012, -0.023, -0.141, 0.592, 0.504, 0.613],
        [0.037, 0.307, -0.031, 0.440, -0.807, 0.243],
        [0.006, 0.072, -0.089, 0.632, 0.149, -0.752],
        [-0.986, 0.120, 0.119, 0.012, 0.002, -0.001]]))